/**
 * The book's boxed "know this by heart" rules, as browsable cards. Hint rung 1
 * deep-links here by `id`, so every ruleId a generator emits should have a card.
 */
export interface RuleCard {
  id: string;
  chapter: number;
  name: string;
  tex: string;
  note: string;
}

/**
 * Several of the boxed rules are really a handful of them under one heading.
 * Run together on one line they read as a wall and wrap wherever the column
 * happens to end; a line each, aligned on the equals sign, is how the book
 * prints them and how they are actually memorised.
 */
function lines(parts: string[]): string {
  return `\\begin{aligned}${parts.join('\\\\')}\\end{aligned}`;
}

export const RULES: readonly RuleCard[] = [
  {
    id: 'sign-rules',
    chapter: 1,
    name: 'Signs',
    tex: lines(['a - (-b) &= a + b', '-(a + b) &= -a - b']),
    note: 'Two minus signs in a row make a plus. A minus in front of a bracket flips everything inside it.',
  },
  {
    id: 'distributive',
    chapter: 1,
    name: 'Distributive law',
    tex: 'a(b \\pm c) = ab \\pm ac',
    note: 'Read right to left it also factorises. It is what makes $47\\cdot 99 = 4700 - 47$ a thing you can do in your head.',
  },
  {
    id: 'rational-equation',
    chapter: 1,
    name: 'Unknown in a denominator',
    tex: '\\frac{a}{b} = \\frac{c}{d} \\iff ad = bc',
    note: 'Multiply out both bars first. Whatever makes a denominator zero was never a solution — check the answer against it.',
  },
  {
    id: 'notable-products',
    chapter: 2,
    name: 'Squaring a binomial',
    tex: '(a\\pm b)^{2}=a^{2}\\pm 2ab+b^{2}',
    note: 'Square the first, twice the product, square the last. The middle term is the one people drop.',
  },
  {
    id: 'difference-of-squares',
    chapter: 2,
    name: 'Difference of squares',
    tex: '(a+b)(a-b)=a^{2}-b^{2}',
    note: 'The two middle terms cancel, which is what makes it worth spotting rather than expanding.',
  },
  {
    id: 'power-rules',
    chapter: 2,
    name: 'Power rules',
    tex: lines(['a^{m}a^{n} &= a^{m+n}', '\\frac{a^{m}}{a^{n}} &= a^{m-n}', '(a^{m})^{n} &= a^{mn}']),
    note: 'Exponents add when the bases multiply, and multiply only when the powers are nested.',
  },
  {
    id: 'cube-of-a-sum',
    chapter: 2,
    name: 'Cube of a sum',
    tex: '(a\\pm b)^{3}=a^{3}\\pm 3a^{2}b+3ab^{2}\\pm b^{3}',
    note: 'Four terms, and the two middle ones carry a 3. With a minus inside, the signs alternate.',
  },
  {
    id: 'power-of-a-product',
    chapter: 2,
    name: 'Power of a product',
    tex: '(ab)^{n}=a^{n}b^{n},\\quad \\left(\\frac{a}{b}\\right)^{n}=\\frac{a^{n}}{b^{n}}',
    note: 'Every factor inside the brackets gets the exponent — the number in front included.',
  },
  {
    id: 'negative-exponent',
    chapter: 2,
    name: 'Negative exponents',
    tex: 'a^{-n}=\\frac{1}{a^{n}}',
    note: 'A negative exponent means a reciprocal, never a negative result.',
  },
  {
    id: 'fraction-add',
    chapter: 3,
    name: 'Adding fractions',
    tex: '\\frac{a}{b}+\\frac{c}{d}=\\frac{ad+bc}{bd}',
    note: 'Any common denominator works; the least one saves the simplifying afterwards.',
  },
  {
    id: 'fraction-multiply',
    chapter: 3,
    name: 'Multiplying and dividing fractions',
    tex: '\\frac{a}{b}\\cdot\\frac{c}{d}=\\frac{ac}{bd},\\quad \\frac{a}{b}\\div\\frac{c}{d}=\\frac{a}{b}\\cdot\\frac{d}{c}',
    note: 'Multiplying needs no common denominator — that is only for adding. Dividing is multiplying by the flipped-over one.',
  },
  {
    id: 'compound-fraction',
    chapter: 3,
    name: 'Fraction inside a fraction',
    tex: '\\frac{\\ \\frac{a}{b}\\ }{\\frac{c}{d}}=\\frac{a}{b}\\cdot\\frac{d}{c}',
    note: 'The main bar is a division. Turn it into one before touching anything else.',
  },
  {
    id: 'rearrange-formula',
    chapter: 3,
    name: 'Rearranging a formula',
    tex: 'A=\\tfrac{1}{2}bh \\Rightarrow h=\\frac{2A}{b}',
    note: 'The same moves as solving for x, with letters where the numbers would be. Get the wanted letter alone on one side.',
  },
  {
    id: 'fraction-simplify',
    chapter: 3,
    name: 'Cancelling',
    tex: '\\frac{ac}{bc}=\\frac{a}{b}',
    note: 'Only whole factors cancel. A term that is added, not multiplied, stays put.',
  },
  {
    id: 'surd-simplify',
    chapter: 4,
    name: 'Simplifying surds',
    tex: '\\sqrt{a^{2}b}=a\\sqrt{b}',
    note: 'Pull out the largest square factor: $\\sqrt{72} = \\sqrt{36\\cdot 2} = 6\\sqrt{2}$.',
  },
  {
    id: 'root-equation',
    chapter: 4,
    name: 'Equation with a root',
    tex: '\\sqrt{f(x)}=c \\Rightarrow f(x)=c^{2},\\ c\\ge 0',
    note: 'Squaring both sides clears the root, but it can invent solutions — every answer has to be put back into the original.',
  },
  {
    id: 'absolute-value',
    chapter: 4,
    name: 'Absolute value',
    tex: '|f(x)|=c \\Rightarrow f(x)=c \\ \\text{or}\\ f(x)=-c',
    note: 'Two cases, always — the bars destroy the sign, so both of them lead back to the same size.',
  },
  {
    id: 'rationalise',
    chapter: 4,
    name: 'Rationalising a denominator',
    tex: '\\frac{1}{\\sqrt{a}+b}=\\frac{\\sqrt{a}-b}{a-b^{2}}',
    note: 'Multiply top and bottom by the conjugate; the denominator loses its root.',
  },
  {
    id: 'fractional-exponent',
    chapter: 4,
    name: 'Fractional exponents',
    tex: 'a^{m/n}=\\sqrt[n]{a^{m}}',
    note: 'The denominator is the root, the numerator is the power. Order does not matter.',
  },
  {
    id: 'log-laws',
    chapter: 6,
    name: 'Log laws',
    tex: lines(['\\log_a(xy) &= \\log_a x + \\log_a y', '\\log_a(x^{n}) &= n\\log_a x']),
    note: 'Products become sums, powers come out front. There is no rule for $\\log(x+y)$.',
  },
  {
    id: 'log-definition',
    chapter: 6,
    name: 'What a logarithm is',
    tex: '\\log_b a = c \\iff b^{c}=a',
    note: 'The logarithm answers one question: what power of the base gives this number? Every log identity is that sentence rearranged.',
  },
  {
    id: 'change-of-base',
    chapter: 6,
    name: 'Change of base',
    tex: '\\log_a x=\\frac{\\ln x}{\\ln a}',
    note: 'The route to any base your calculator lacks.',
  },
  {
    id: 'exp-log-inverse',
    chapter: 6,
    name: 'exp and ln undo each other',
    tex: lines(['e^{\\ln x} &= x', '\\ln(e^{x}) &= x']),
    note: 'So $e^{3\\ln t}$ is $t^{3}$ — bring the 3 inside first.',
  },
  {
    id: 'exponential-equation',
    chapter: 6,
    name: 'Solving an exponential equation',
    tex: 'a^{x}=b\\iff x=\\frac{\\ln b}{\\ln a}',
    note: 'Take logs of both sides; the unknown comes down from the exponent.',
  },
  {
    id: 'radians',
    chapter: 7,
    name: 'Degrees and radians',
    tex: '180^\\circ=\\pi\\ \\text{rad}',
    note: 'Multiply by $\\pi/180$ to go to radians, by $180/\\pi$ to come back.',
  },
  {
    id: 'pythagorean-identity',
    chapter: 7,
    name: 'Pythagorean identity',
    tex: '\\sin^{2}x+\\cos^{2}x=1',
    note: 'The one identity everything else in the chapter is built from.',
  },
  {
    id: 'double-angle',
    chapter: 7,
    name: 'Double angle',
    tex: lines(['\\sin 2x &= 2\\sin x\\cos x', '\\cos 2x &= 1 - 2\\sin^{2}x']),
    note: '$\\cos 2x$ has three equivalent forms; pick whichever leaves the tidier expression.',
  },
  {
    id: 'addition-formulas',
    chapter: 7,
    name: 'Addition formulas',
    tex: lines([
      '\\sin(u\\pm v) &= \\sin u\\cos v \\pm \\cos u\\sin v',
      '\\cos(u\\pm v) &= \\cos u\\cos v \\mp \\sin u\\sin v',
    ]),
    note: 'The cosine one swaps the sign — a plus inside gives a minus outside. Everything else in the chapter, the double angles included, comes from these two.',
  },
  {
    id: 'shift-identities',
    chapter: 7,
    name: 'Shifts and reflections',
    tex: lines([
      '\\sin(-x) &= -\\sin x, \\quad \\cos(-x) = \\cos x',
      '\\sin(x+\\pi) &= -\\sin x, \\quad \\cos(x+\\pi) = -\\cos x',
      '\\cos\\left(\\tfrac{\\pi}{2}-x\\right) &= \\sin x',
    ]),
    note: 'Shifting by a whole period changes nothing, by half a period flips the sign, and by a quarter swaps sine and cosine. Read them off the unit circle rather than memorising them.',
  },
  {
    id: 'trig-equation',
    chapter: 7,
    name: 'Solving a trig equation',
    tex: '\\sin x = s \\Rightarrow x = \\alpha \\ \\text{or}\\ x = \\pi - \\alpha \\ (+2k\\pi)',
    note: 'Two solutions per turn, not one. For a cosine the partner is $2\\pi-\\alpha$; sketch the unit circle and read both off it.',
  },
  {
    id: 'exact-values',
    chapter: 7,
    name: 'Exact values',
    tex: lines([
      '\\sin\\tfrac{\\pi}{6} &= \\tfrac{1}{2}',
      '\\sin\\tfrac{\\pi}{4} &= \\tfrac{1}{2}\\sqrt{2}',
      '\\sin\\tfrac{\\pi}{3} &= \\tfrac{1}{2}\\sqrt{3}',
    ]),
    note: 'Know the 30–60–90 and 45–45–90 triangles and the rest follow.',
  },
  {
    id: 'quadratic-formula',
    chapter: 8,
    name: 'Quadratic formula',
    tex: 'x=\\frac{-b\\pm\\sqrt{b^{2}-4ac}}{2a}',
    note: 'The discriminant $b^{2}-4ac$ tells you how many real roots there are before you solve.',
  },
  {
    id: 'inequality',
    chapter: 8,
    name: 'Inequalities',
    tex: 'a < b \\Rightarrow -a > -b',
    note: 'Multiplying or dividing by a negative number turns the sign round. For a quadratic, find where it is zero first — the sign can only change there.',
  },
  {
    id: 'completing-square',
    chapter: 8,
    name: 'Completing the square',
    tex: 'x^{2}+bx+c=\\left(x+\\tfrac{b}{2}\\right)^{2}+c-\\tfrac{b^{2}}{4}',
    note: 'Half the coefficient of x goes inside the bracket, and its square is then subtracted back out. This is where the quadratic formula comes from, and it is what shows you the vertex.',
  },
  {
    id: 'linear-system',
    chapter: 8,
    name: 'Two equations, two unknowns',
    tex: '\\begin{cases}a x + b y = p\\\\ c x + d y = q\\end{cases}',
    note: 'Eliminate one unknown by adding a multiple of one equation to the other, solve for the one that is left, and substitute back.',
  },
  {
    id: 'linear-solve',
    chapter: 8,
    name: 'Solving a linear equation',
    tex: 'ax+b=cx+d\\iff x=\\frac{d-b}{a-c}',
    note: 'Collect the unknowns on one side, the numbers on the other, then divide once.',
  },
  {
    id: 'power-rule',
    chapter: 9,
    name: 'Power rule',
    tex: '\\frac{d}{dx}x^{n}=nx^{n-1}',
    note: 'Works for every real $n$, including negative and fractional ones.',
  },
  {
    id: 'chain-rule',
    chapter: 9,
    name: 'Chain rule',
    tex: '\\frac{d}{dx}f(g(x))=f\'(g(x))\\cdot g\'(x)',
    note: 'Differentiate the outside at the inside, then multiply by the derivative of the inside.',
  },
  {
    id: 'product-rule',
    chapter: 9,
    name: 'Product rule',
    tex: '(uv)\'=u\'v+uv\'',
    note: 'Both terms, always. The derivative of a product is not the product of derivatives.',
  },
  {
    id: 'quotient-rule',
    chapter: 9,
    name: 'Quotient rule',
    tex: '\\left(\\frac{u}{v}\\right)\'=\\frac{u\'v-uv\'}{v^{2}}',
    note: "The numerator subtracts, so the order matters — $u'v$ comes first.",
  },
  {
    id: 'standard-derivatives',
    chapter: 9,
    name: 'Standard derivatives',
    tex: lines([
      "(\\sin x)' &= \\cos x",
      "(\\cos x)' &= -\\sin x",
      "(e^{x})' &= e^{x}",
      "(\\ln x)' &= \\tfrac{1}{x}",
    ]),
    note: 'The minus on the derivative of cos is the one that gets forgotten.',
  },
  {
    id: 'tangent-line',
    chapter: 9,
    name: 'Tangent line',
    tex: 'y = f\'(a)(x-a) + f(a)',
    note: 'The derivative only gives the slope. The line still has to pass through the point, which is what the rest of it is for.',
  },
  {
    id: 'stationary-point',
    chapter: 9,
    name: 'Stationary points',
    tex: 'f\'(x) = 0',
    note: 'A maximum or a minimum has a horizontal tangent, so solving $f\'(x)=0$ finds the candidates. Which kind each one is comes from the sign of $f\'$ around it.',
  },
  {
    id: 'antiderivative-power',
    chapter: 10,
    name: 'Antiderivative of a power',
    tex: '\\int x^{n}\\,dx=\\frac{x^{n+1}}{n+1}+C,\\quad n\\neq-1',
    note: '$n = -1$ is the exception: that integral is $\\ln|x| + C$.',
  },
  {
    id: 'standard-antiderivatives',
    chapter: 10,
    name: 'Standard antiderivatives',
    tex: lines([
      '\\int e^{x}\\,dx &= e^{x} + C',
      '\\int \\sin x\\,dx &= -\\cos x + C',
      '\\int \\cos x\\,dx &= \\sin x + C',
      '\\int \\tfrac{1}{x}\\,dx &= \\ln|x| + C',
    ]),
    note: 'The derivative table read backwards. The minus moves to the antiderivative of sin, which is where it gets forgotten.',
  },
  {
    id: 'linear-substitution',
    chapter: 10,
    name: 'Linear inner function',
    tex: '\\int f(ax+b)\\,dx=\\frac{1}{a}F(ax+b)+C',
    note: 'Divide by the derivative of the inside — but only when the inside is linear.',
  },
  {
    id: 'log-antiderivative',
    chapter: 10,
    name: 'The n = −1 case',
    tex: lines([
      '\\int \\tfrac{1}{x}\\,dx &= \\ln|x| + C',
      '\\int \\tfrac{1}{ax+b}\\,dx &= \\tfrac{1}{a}\\ln|ax+b| + C',
    ]),
    note: 'The power rule divides by $n+1$, which is zero here. The bars matter: the integrand is defined on both sides of the origin and $\\ln$ is not.',
  },
  {
    id: 'reverse-chain',
    chapter: 10,
    name: 'Recognising a derivative',
    tex: lines([
      "\\int f'(x)\\,g'(f(x))\\,dx &= g(f(x)) + C",
      "\\int \\tfrac{f'(x)}{f(x)}\\,dx &= \\ln|f(x)| + C",
    ]),
    note: 'Look for the inside function and its derivative sitting in the same integrand. Spotting it is the whole exercise — there is nothing to compute once you have.',
  },
  {
    id: 'by-parts',
    chapter: 10,
    name: 'Integration by parts',
    tex: "\\int u\\,v'\\,dx = uv - \\int u'\\,v\\,dx",
    note: 'Pick $u$ to be the part that gets simpler when differentiated — a power of $x$, or $\\ln x$. If the new integral is worse than the old one, you chose the other way round.',
  },
  {
    id: 'partial-fractions',
    chapter: 10,
    name: 'Splitting a fraction',
    tex: '\\frac{1}{(x-p)(x-q)} = \\frac{1}{p-q}\\left(\\frac{1}{x-p} - \\frac{1}{x-q}\\right)',
    note: 'Nothing integrates a product of two brackets in a denominator; a sum of two simple ones integrates term by term. Factorise first, then find the numerators by comparing coefficients.',
  },
  {
    id: 'polynomial-division',
    chapter: 10,
    name: 'Dividing first',
    tex: '\\frac{N(x)}{D(x)} = Q(x) + \\frac{R(x)}{D(x)}',
    note: 'When the top is the same degree as the bottom or higher, divide. What is left over has a smaller degree than the divisor, and only then is it a shape you have a rule for.',
  },
  {
    id: 'plus-c',
    chapter: 10,
    name: 'The constant of integration',
    tex: '\\int f(x)\\,dx=F(x)+C',
    note: 'An indefinite integral is a family of functions. Without the $+C$ the answer names only one.',
  },
  {
    id: 'definite-integral',
    chapter: 11,
    name: 'Definite integral',
    tex: '\\int_a^b f(x)\\,dx=F(b)-F(a)',
    note: 'No $+C$ once the bounds go in — it cancels.',
  },
  {
    id: 'total-area',
    chapter: 11,
    name: 'Total area',
    tex: 'A=\\int_a^b \\left|f(x)\\right|dx',
    note: 'Where the curve crosses the axis, the integral counts the part underneath as negative. Area does not work that way: split at the crossing and add the sizes.',
  },
  {
    id: 'area-about-y',
    chapter: 11,
    name: 'Area against the y-axis',
    tex: 'A=\\int_c^d g(y)\\,dy',
    note: 'A region held between a curve and the y-axis is measured in horizontal strips, so everything — the function and the bounds — has to be written in $y$.',
  },
  {
    id: 'limit-factor',
    chapter: 13,
    name: 'A limit that looks like 0/0',
    tex: '\\lim_{x\\to a}\\frac{(x-a)g(x)}{(x-a)h(x)} = \\lim_{x\\to a}\\frac{g(x)}{h(x)}',
    note: 'Substituting gives 0/0, which says nothing. The factor causing it cancels — x never actually equals a, so dividing by $x-a$ is allowed.',
  },
  {
    id: 'limit-infinity',
    chapter: 13,
    name: 'Limits at infinity',
    tex: '\\lim_{x\\to\\infty}\\frac{a_nx^{n}+\\dots}{b_mx^{m}+\\dots} = \\begin{cases}0 & n<m\\\\ \\frac{a_n}{b_m} & n=m\\end{cases}',
    note: 'Divide top and bottom by the highest power in the bottom. Everything with an x left underneath it goes to zero and only the leading behaviour survives.',
  },
  {
    id: 'lhopital',
    chapter: 13,
    name: "L'Hôpital's rule",
    tex: '\\lim_{x\\to a}\\frac{f(x)}{g(x)} = \\lim_{x\\to a}\\frac{f\'(x)}{g\'(x)}',
    note: 'Only for 0/0 and ∞/∞, and it is the derivatives separately — never the quotient rule. Check the form before using it, every time.',
  },
  {
    id: 'continuity',
    chapter: 13,
    name: 'Continuity at a point',
    tex: '\\lim_{x\\uparrow a}f(x) = \\lim_{x\\downarrow a}f(x) = f(a)',
    note: 'Three things, all equal: what it approaches from the left, from the right, and what it actually is there. A piecewise definition is continuous exactly where the two pieces meet.',
  },
  {
    id: 'asymptote',
    chapter: 13,
    name: 'Asymptotes',
    tex: lines([
      '\\text{vertical} &: \\text{where the denominator is } 0',
      '\\text{horizontal} &: y = \\lim_{x\\to\\pm\\infty}f(x)',
      '\\text{slant} &: \\text{the quotient after dividing}',
    ]),
    note: 'A slant asymptote appears exactly when the top is one degree higher than the bottom — divide, and the remainder dies away.',
  },
  {
    id: 'domain',
    chapter: 5,
    name: 'Domain',
    tex: lines([
      '\\text{fraction} &: \\text{bottom} \\ne 0',
      '\\sqrt{\\ } &: \\text{inside} \\ge 0',
      '\\ln &: \\text{inside} > 0',
    ]),
    note: 'Three things can go wrong and nothing else can. Cancelling a factor does not repair the hole it came from — the function still has no value there.',
  },
  {
    id: 'range',
    chapter: 5,
    name: 'Range',
    tex: '\\text{R}(f) = \\{f(x) : x \\in \\text{D}(f)\\}',
    note: 'Work outwards from the part that is bounded — a square is at least 0, a root is at least 0, a bounded bottom keeps a fraction bounded. Then ask whether the extreme is actually reached or only approached.',
  },
  {
    id: 'parity',
    chapter: 5,
    name: 'Even and odd',
    tex: lines(['\\text{even} &: f(-x) = f(x)', '\\text{odd} &: f(-x) = -f(x)']),
    note: 'Substitute, do not squint at the graph. Even times odd is odd, odd over odd is even, and an even inside makes the whole composition even whatever is outside it.',
  },
  {
    id: 'inverse',
    chapter: 5,
    name: 'Inverse function',
    tex: 'y = f(x) \\iff x = f^{-1}(y)',
    note: 'Swap x and y, then solve for y. When y appears twice, collect it on one side before dividing.',
  },
  {
    id: 'composition',
    chapter: 5,
    name: 'Composition',
    tex: '(f \\circ g)(x) = f(g(x))',
    note: "The whole of g goes wherever f's x was. f(g(x)) and g(f(x)) are different functions, and the composition is only defined where g's output is in f's domain.",
  },
  {
    id: 'derivative-definition',
    chapter: 9,
    name: 'Definition of the derivative',
    tex: "f'(a) = \\lim_{h\\to 0}\\frac{f(a+h)-f(a)}{h}",
    note: 'Every rule in the chapter is a shortcut for this. The h in the bottom always cancels — if it does not, the expansion has gone wrong.',
  },
  {
    id: 'higher-derivatives',
    chapter: 9,
    name: 'Higher derivatives',
    tex: "f^{(n)}(x) = \\frac{d}{dx}f^{(n-1)}(x)",
    note: 'For a large n, find the first three or four and look for the cycle rather than grinding: sin and cos repeat every four, and 1/x picks up a factorial and a sign each time.',
  },
  {
    id: 'logarithmic-differentiation',
    chapter: 9,
    name: 'Logarithmic differentiation',
    tex: "\\ln f = g \\Rightarrow f' = f\\cdot g'",
    note: 'For an x in the exponent and an x in the base at once, where neither the power rule nor the exponential rule applies. Take ln, differentiate, multiply back by f.',
  },
  {
    id: 'squeeze',
    chapter: 13,
    name: 'Squeeze theorem',
    tex: 'g \\le f \\le h \\text{ and } \\lim g = \\lim h = L \\Rightarrow \\lim f = L',
    note: "For a factor that oscillates and has no limit of its own. Bound it between -1 and 1, multiply through by the part that does go somewhere, and the middle has nowhere else to go. L'Hôpital cannot help here.",
  },
  {
    id: 'limit-exponential',
    chapter: 13,
    name: 'The 1 to the infinity form',
    tex: '\\lim_{x\\to\\infty}\\left(1+\\frac{a}{x}\\right)^{x} = e^{a}',
    note: 'A base creeping to 1 with an exponent running to infinity is not 1 — the two race, and e is the result. Force the expression into this shape rather than guessing.',
  },
  {
    id: 'slope',
    chapter: 5,
    name: 'Slope of a line',
    tex: 'm = \\frac{y_2 - y_1}{x_2 - x_1}, \\quad y = mx + q',
    note: 'Both differences in the same order, or the sign comes out backwards. Once m is known, either point gives q.',
  },
  {
    id: 'circle',
    chapter: 5,
    name: 'Equation of a circle',
    tex: '(x-h)^{2} + (y-k)^{2} = r^{2}',
    note: 'Centre (h, k) — the signs in the brackets are the opposite of the centre. The right-hand side is r squared, not r.',
  },
  {
    id: 'vector-arithmetic',
    chapter: 12,
    name: 'Adding and scaling vectors',
    tex: lines([
      '\\vec{a} \\pm \\vec{b} &= \\begin{pmatrix}a_1 \\pm b_1\\\\a_2 \\pm b_2\\end{pmatrix}',
      'k\\vec{a} &= \\begin{pmatrix}ka_1\\\\ka_2\\end{pmatrix}',
      '\\vec{PQ} &= \\vec{q} - \\vec{p}',
    ]),
    note: 'Componentwise, always. Drawn, a sum is tip to tail; head minus tail is the arrow between two points, in that order.',
  },
  {
    id: 'vector-length',
    chapter: 12,
    name: 'Length of a vector',
    tex: '\\left|\\vec{a}\\right| = \\sqrt{a_1^{2}+a_2^{2}}',
    note: 'Pythagoras on the components. Leave the root standing — an exact length is the answer, a decimal is not.',
  },
  {
    id: 'dot-product',
    chapter: 12,
    name: 'Dot product',
    tex: lines([
      '\\vec{a}\\cdot\\vec{b} &= a_1b_1 + a_2b_2',
      '&= \\left|\\vec{a}\\right|\\left|\\vec{b}\\right|\\cos\\theta',
    ]),
    note: 'It produces a number, not a vector. Zero means perpendicular; the sign of the dot product is the sign of the cosine, so it tells you sharp or blunt without finding the angle.',
  },
  {
    id: 'area-between',
    chapter: 11,
    name: 'Area between two curves',
    tex: 'A=\\int_a^b \\left(f(x)-g(x)\\right)dx',
    note: 'Upper curve minus lower, and split the integral wherever they cross.',
  },
];

export function ruleById(id: string): RuleCard | undefined {
  return RULES.find((r) => r.id === id);
}
