import { lines, type RuleCard } from './card.js';

/** The algebra, functions and equations of chapters 1 to 8. */
export const ALGEBRA_RULES: readonly RuleCard[] = [
  {
    id: 'sign-rules',
    chapter: 1,
    name: 'Signs',
    tex: lines(['a - (-b) &= a + b', '-(a + b) &= -a - b']),
    note: 'Two minus signs in a row make a plus. A minus in front of a bracket flips everything inside it.',
  },
  {
    id: 'distributive',
    chapter: 1,
    name: 'Distributive law',
    tex: 'a(b \\pm c) = ab \\pm ac',
    note: 'Read right to left it also factorises. It is what makes $47\\cdot 99 = 4700 - 47$ a thing you can do in your head.',
  },
  {
    id: 'rational-equation',
    chapter: 1,
    name: 'Unknown in a denominator',
    tex: '\\frac{a}{b} = \\frac{c}{d} \\iff ad = bc',
    note: 'Multiply out both bars first. Whatever makes a denominator zero was never a solution — check the answer against it.',
  },
  {
    id: 'notable-products',
    chapter: 2,
    name: 'Squaring a binomial',
    tex: '(a\\pm b)^{2}=a^{2}\\pm 2ab+b^{2}',
    note: 'Square the first, twice the product, square the last. The middle term is the one people drop.',
  },
  {
    id: 'difference-of-squares',
    chapter: 2,
    name: 'Difference of squares',
    tex: '(a+b)(a-b)=a^{2}-b^{2}',
    note: 'The two middle terms cancel, which is what makes it worth spotting rather than expanding.',
  },
  {
    id: 'power-rules',
    chapter: 2,
    name: 'Power rules',
    tex: lines(['a^{m}a^{n} &= a^{m+n}', '\\frac{a^{m}}{a^{n}} &= a^{m-n}', '(a^{m})^{n} &= a^{mn}']),
    note: 'Exponents add when the bases multiply, and multiply only when the powers are nested.',
  },
  {
    id: 'cube-of-a-sum',
    chapter: 2,
    name: 'Cube of a sum',
    tex: '(a\\pm b)^{3}=a^{3}\\pm 3a^{2}b+3ab^{2}\\pm b^{3}',
    note: 'Four terms, and the two middle ones carry a 3. With a minus inside, the signs alternate.',
  },
  {
    id: 'power-of-a-product',
    chapter: 2,
    name: 'Power of a product',
    tex: '(ab)^{n}=a^{n}b^{n},\\quad \\left(\\frac{a}{b}\\right)^{n}=\\frac{a^{n}}{b^{n}}',
    note: 'Every factor inside the brackets gets the exponent — the number in front included.',
  },
  {
    id: 'negative-exponent',
    chapter: 2,
    name: 'Negative exponents',
    tex: 'a^{-n}=\\frac{1}{a^{n}}',
    note: 'A negative exponent means a reciprocal, never a negative result.',
  },
  {
    id: 'fraction-add',
    chapter: 3,
    name: 'Adding fractions',
    tex: '\\frac{a}{b}+\\frac{c}{d}=\\frac{ad+bc}{bd}',
    note: 'Any common denominator works; the least one saves the simplifying afterwards.',
  },
  {
    id: 'fraction-multiply',
    chapter: 3,
    name: 'Multiplying and dividing fractions',
    tex: '\\frac{a}{b}\\cdot\\frac{c}{d}=\\frac{ac}{bd},\\quad \\frac{a}{b}\\div\\frac{c}{d}=\\frac{a}{b}\\cdot\\frac{d}{c}',
    note: 'Multiplying needs no common denominator — that is only for adding. Dividing is multiplying by the flipped-over one.',
  },
  {
    id: 'compound-fraction',
    chapter: 3,
    name: 'Fraction inside a fraction',
    tex: '\\frac{\\ \\frac{a}{b}\\ }{\\frac{c}{d}}=\\frac{a}{b}\\cdot\\frac{d}{c}',
    note: 'The main bar is a division. Turn it into one before touching anything else.',
  },
  {
    id: 'rearrange-formula',
    chapter: 3,
    name: 'Rearranging a formula',
    tex: 'A=\\tfrac{1}{2}bh \\Rightarrow h=\\frac{2A}{b}',
    note: 'The same moves as solving for x, with letters where the numbers would be. Get the wanted letter alone on one side.',
  },
  {
    id: 'fraction-simplify',
    chapter: 3,
    name: 'Cancelling',
    tex: '\\frac{ac}{bc}=\\frac{a}{b}',
    note: 'Only whole factors cancel. A term that is added, not multiplied, stays put.',
  },
  {
    id: 'surd-simplify',
    chapter: 4,
    name: 'Simplifying surds',
    tex: '\\sqrt{a^{2}b}=a\\sqrt{b}',
    note: 'Pull out the largest square factor: $\\sqrt{72} = \\sqrt{36\\cdot 2} = 6\\sqrt{2}$.',
  },
  {
    id: 'root-equation',
    chapter: 4,
    name: 'Equation with a root',
    tex: '\\sqrt{f(x)}=c \\Rightarrow f(x)=c^{2},\\ c\\ge 0',
    note: 'Squaring both sides clears the root, but it can invent solutions — every answer has to be put back into the original.',
  },
  {
    id: 'absolute-value',
    chapter: 4,
    name: 'Absolute value',
    tex: '|f(x)|=c \\Rightarrow f(x)=c \\ \\text{or}\\ f(x)=-c',
    note: 'Two cases, always — the bars destroy the sign, so both of them lead back to the same size.',
  },
  {
    id: 'rationalise',
    chapter: 4,
    name: 'Rationalising a denominator',
    tex: '\\frac{1}{\\sqrt{a}+b}=\\frac{\\sqrt{a}-b}{a-b^{2}}',
    note: 'Multiply top and bottom by the conjugate; the denominator loses its root.',
  },
  {
    id: 'fractional-exponent',
    chapter: 4,
    name: 'Fractional exponents',
    tex: 'a^{m/n}=\\sqrt[n]{a^{m}}',
    note: 'The denominator is the root, the numerator is the power. Order does not matter.',
  },
  {
    id: 'log-laws',
    chapter: 6,
    name: 'Log laws',
    tex: lines(['\\log_a(xy) &= \\log_a x + \\log_a y', '\\log_a(x^{n}) &= n\\log_a x']),
    note: 'Products become sums, powers come out front. There is no rule for $\\log(x+y)$.',
  },
  {
    id: 'log-definition',
    chapter: 6,
    name: 'What a logarithm is',
    tex: '\\log_b a = c \\iff b^{c}=a',
    note: 'The logarithm answers one question: what power of the base gives this number? Every log identity is that sentence rearranged.',
  },
  {
    id: 'change-of-base',
    chapter: 6,
    name: 'Change of base',
    tex: '\\log_a x=\\frac{\\ln x}{\\ln a}',
    note: 'The route to any base your calculator lacks.',
  },
  {
    id: 'exp-log-inverse',
    chapter: 6,
    name: 'exp and ln undo each other',
    tex: lines(['e^{\\ln x} &= x', '\\ln(e^{x}) &= x']),
    note: 'So $e^{3\\ln t}$ is $t^{3}$ — bring the 3 inside first.',
  },
  {
    id: 'exponential-equation',
    chapter: 6,
    name: 'Solving an exponential equation',
    tex: 'a^{x}=b\\iff x=\\frac{\\ln b}{\\ln a}',
    note: 'Take logs of both sides; the unknown comes down from the exponent.',
  },
  {
    id: 'radians',
    chapter: 7,
    name: 'Degrees and radians',
    tex: '180^\\circ=\\pi\\ \\text{rad}',
    note: 'Multiply by $\\pi/180$ to go to radians, by $180/\\pi$ to come back.',
  },
  {
    id: 'pythagorean-identity',
    chapter: 7,
    name: 'Pythagorean identity',
    tex: '\\sin^{2}x+\\cos^{2}x=1',
    note: 'The one identity everything else in the chapter is built from.',
  },
  {
    id: 'double-angle',
    chapter: 7,
    name: 'Double angle',
    tex: lines(['\\sin 2x &= 2\\sin x\\cos x', '\\cos 2x &= 1 - 2\\sin^{2}x']),
    note: '$\\cos 2x$ has three equivalent forms; pick whichever leaves the tidier expression.',
  },
  {
    id: 'addition-formulas',
    chapter: 7,
    name: 'Addition formulas',
    tex: lines([
      '\\sin(u\\pm v) &= \\sin u\\cos v \\pm \\cos u\\sin v',
      '\\cos(u\\pm v) &= \\cos u\\cos v \\mp \\sin u\\sin v',
    ]),
    note: 'The cosine one swaps the sign — a plus inside gives a minus outside. Everything else in the chapter, the double angles included, comes from these two.',
  },
  {
    id: 'shift-identities',
    chapter: 7,
    name: 'Shifts and reflections',
    tex: lines([
      '\\sin(-x) &= -\\sin x, \\quad \\cos(-x) = \\cos x',
      '\\sin(x+\\pi) &= -\\sin x, \\quad \\cos(x+\\pi) = -\\cos x',
      '\\cos\\left(\\tfrac{\\pi}{2}-x\\right) &= \\sin x',
    ]),
    note: 'Shifting by a whole period changes nothing, by half a period flips the sign, and by a quarter swaps sine and cosine. Read them off the unit circle rather than memorising them.',
  },
  {
    id: 'trig-equation',
    chapter: 7,
    name: 'Solving a trig equation',
    tex: '\\sin x = s \\Rightarrow x = \\alpha \\ \\text{or}\\ x = \\pi - \\alpha \\ (+2k\\pi)',
    note: 'Two solutions per turn, not one. For a cosine the partner is $2\\pi-\\alpha$; sketch the unit circle and read both off it.',
  },
  {
    id: 'exact-values',
    chapter: 7,
    name: 'Exact values',
    tex: lines([
      '\\sin\\tfrac{\\pi}{6} &= \\tfrac{1}{2}',
      '\\sin\\tfrac{\\pi}{4} &= \\tfrac{1}{2}\\sqrt{2}',
      '\\sin\\tfrac{\\pi}{3} &= \\tfrac{1}{2}\\sqrt{3}',
    ]),
    note: 'Know the 30–60–90 and 45–45–90 triangles and the rest follow.',
  },
  {
    id: 'quadratic-formula',
    chapter: 8,
    name: 'Quadratic formula',
    tex: 'x=\\frac{-b\\pm\\sqrt{b^{2}-4ac}}{2a}',
    note: 'The discriminant $b^{2}-4ac$ tells you how many real roots there are before you solve.',
  },
  {
    id: 'inequality',
    chapter: 8,
    name: 'Inequalities',
    tex: 'a < b \\Rightarrow -a > -b',
    note: 'Multiplying or dividing by a negative number turns the sign round. For a quadratic, find where it is zero first — the sign can only change there.',
  },
  {
    id: 'completing-square',
    chapter: 8,
    name: 'Completing the square',
    tex: 'x^{2}+bx+c=\\left(x+\\tfrac{b}{2}\\right)^{2}+c-\\tfrac{b^{2}}{4}',
    note: 'Half the coefficient of x goes inside the bracket, and its square is then subtracted back out. This is where the quadratic formula comes from, and it is what shows you the vertex.',
  },
  {
    id: 'linear-system',
    chapter: 8,
    name: 'Two equations, two unknowns',
    tex: '\\begin{cases}a x + b y = p\\\\ c x + d y = q\\end{cases}',
    note: 'Eliminate one unknown by adding a multiple of one equation to the other, solve for the one that is left, and substitute back.',
  },
  {
    id: 'linear-solve',
    chapter: 8,
    name: 'Solving a linear equation',
    tex: 'ax+b=cx+d\\iff x=\\frac{d-b}{a-c}',
    note: 'Collect the unknowns on one side, the numbers on the other, then divide once.',
  },
  {
    id: 'domain',
    chapter: 5,
    name: 'Domain',
    tex: lines([
      '\\text{fraction} &: \\text{bottom} \\ne 0',
      '\\sqrt{\\ } &: \\text{inside} \\ge 0',
      '\\ln &: \\text{inside} > 0',
    ]),
    note: 'Three things can go wrong and nothing else can. Cancelling a factor does not repair the hole it came from — the function still has no value there.',
  },
  {
    id: 'range',
    chapter: 5,
    name: 'Range',
    tex: '\\text{R}(f) = \\{f(x) : x \\in \\text{D}(f)\\}',
    note: 'Work outwards from the part that is bounded — a square is at least 0, a root is at least 0, a bounded bottom keeps a fraction bounded. Then ask whether the extreme is actually reached or only approached.',
  },
  {
    id: 'parity',
    chapter: 5,
    name: 'Even and odd',
    tex: lines(['\\text{even} &: f(-x) = f(x)', '\\text{odd} &: f(-x) = -f(x)']),
    note: 'Substitute, do not squint at the graph. Even times odd is odd, odd over odd is even, and an even inside makes the whole composition even whatever is outside it.',
  },
  {
    id: 'inverse',
    chapter: 5,
    name: 'Inverse function',
    tex: 'y = f(x) \\iff x = f^{-1}(y)',
    note: 'Swap x and y, then solve for y. When y appears twice, collect it on one side before dividing.',
  },
  {
    id: 'composition',
    chapter: 5,
    name: 'Composition',
    tex: '(f \\circ g)(x) = f(g(x))',
    note: "The whole of g goes wherever f's x was. f(g(x)) and g(f(x)) are different functions, and the composition is only defined where g's output is in f's domain.",
  },
  {
    id: 'slope',
    chapter: 5,
    name: 'Slope of a line',
    tex: 'm = \\frac{y_2 - y_1}{x_2 - x_1}, \\quad y = mx + q',
    note: 'Both differences in the same order, or the sign comes out backwards. Once m is known, either point gives q.',
  },
  {
    id: 'circle',
    chapter: 5,
    name: 'Equation of a circle',
    tex: '(x-h)^{2} + (y-k)^{2} = r^{2}',
    note: 'Centre (h, k) — the signs in the brackets are the opposite of the centre. The right-hand side is r squared, not r.',
  },
];
