import { lines, type RuleCard } from './card.js';

/** The calculus, vectors and limits of chapters 9 to 13. */
export const CALCULUS_RULES: readonly RuleCard[] = [
  {
    id: 'power-rule',
    chapter: 9,
    name: 'Power rule',
    tex: '\\frac{d}{dx}x^{n}=nx^{n-1}',
    note: 'Works for every real $n$, including negative and fractional ones.',
  },
  {
    id: 'chain-rule',
    chapter: 9,
    name: 'Chain rule',
    tex: '\\frac{d}{dx}f(g(x))=f\'(g(x))\\cdot g\'(x)',
    note: 'Differentiate the outside at the inside, then multiply by the derivative of the inside.',
  },
  {
    id: 'product-rule',
    chapter: 9,
    name: 'Product rule',
    tex: '(uv)\'=u\'v+uv\'',
    note: 'Both terms, always. The derivative of a product is not the product of derivatives.',
  },
  {
    id: 'quotient-rule',
    chapter: 9,
    name: 'Quotient rule',
    tex: '\\left(\\frac{u}{v}\\right)\'=\\frac{u\'v-uv\'}{v^{2}}',
    note: "The numerator subtracts, so the order matters — $u'v$ comes first.",
  },
  {
    id: 'standard-derivatives',
    chapter: 9,
    name: 'Standard derivatives',
    tex: lines([
      "(\\sin x)' &= \\cos x",
      "(\\cos x)' &= -\\sin x",
      "(e^{x})' &= e^{x}",
      "(\\ln x)' &= \\tfrac{1}{x}",
    ]),
    note: 'The minus on the derivative of cos is the one that gets forgotten.',
  },
  {
    id: 'tangent-line',
    chapter: 9,
    name: 'Tangent line',
    tex: 'y = f\'(a)(x-a) + f(a)',
    note: 'The derivative only gives the slope. The line still has to pass through the point, which is what the rest of it is for.',
  },
  {
    id: 'stationary-point',
    chapter: 9,
    name: 'Stationary points',
    tex: 'f\'(x) = 0',
    note: 'A maximum or a minimum has a horizontal tangent, so solving $f\'(x)=0$ finds the candidates. Which kind each one is comes from the sign of $f\'$ around it.',
  },
  {
    id: 'optimisation',
    chapter: 9,
    name: 'Optimising a quantity',
    tex: lines([
      'Q(x, y),\\ \\text{constraint} &\\;\\Rightarrow\\; Q(x)',
      "Q'(x) &= 0",
      "Q''(x) < 0 &\\;\\Rightarrow\\; \\text{a maximum}",
    ]),
    note: 'Write down the quantity, use the constraint to get rid of every variable but one, and only then differentiate. Keep to the values the problem allows — a side is never negative — and check the candidate is the kind of extreme you were asked for.',
  },
  {
    id: 'antiderivative-power',
    chapter: 10,
    name: 'Antiderivative of a power',
    tex: '\\int x^{n}\\,dx=\\frac{x^{n+1}}{n+1}+C,\\quad n\\neq-1',
    note: '$n = -1$ is the exception: that integral is $\\ln|x| + C$.',
  },
  {
    id: 'standard-antiderivatives',
    chapter: 10,
    name: 'Standard antiderivatives',
    tex: lines([
      '\\int e^{x}\\,dx &= e^{x} + C',
      '\\int \\sin x\\,dx &= -\\cos x + C',
      '\\int \\cos x\\,dx &= \\sin x + C',
      '\\int \\tfrac{1}{x}\\,dx &= \\ln|x| + C',
    ]),
    note: 'The derivative table read backwards. The minus moves to the antiderivative of sin, which is where it gets forgotten.',
  },
  {
    id: 'linear-substitution',
    chapter: 10,
    name: 'Linear inner function',
    tex: '\\int f(ax+b)\\,dx=\\frac{1}{a}F(ax+b)+C',
    note: 'Divide by the derivative of the inside — but only when the inside is linear.',
  },
  {
    id: 'log-antiderivative',
    chapter: 10,
    name: 'The n = −1 case',
    tex: lines([
      '\\int \\tfrac{1}{x}\\,dx &= \\ln|x| + C',
      '\\int \\tfrac{1}{ax+b}\\,dx &= \\tfrac{1}{a}\\ln|ax+b| + C',
    ]),
    note: 'The power rule divides by $n+1$, which is zero here. The bars matter: the integrand is defined on both sides of the origin and $\\ln$ is not.',
  },
  {
    id: 'reverse-chain',
    chapter: 10,
    name: 'Recognising a derivative',
    tex: lines([
      "\\int f'(x)\\,g'(f(x))\\,dx &= g(f(x)) + C",
      "\\int \\tfrac{f'(x)}{f(x)}\\,dx &= \\ln|f(x)| + C",
    ]),
    note: 'Look for the inside function and its derivative sitting in the same integrand. Spotting it is the whole exercise — there is nothing to compute once you have.',
  },
  {
    id: 'substitution',
    chapter: 10,
    name: 'Substitution',
    tex: lines([
      'u = g(x),\\quad du &= g\'(x)\\,dx',
      '\\int_{a}^{b} f(g(x))\\,g\'(x)\\,dx &= \\int_{g(a)}^{g(b)} f(u)\\,du',
    ]),
    note: 'Every $x$ has to go, not just the inside: solve $u = g(x)$ for $x$ and write what is left over in $u$. On a definite integral the bounds move with it, and there is no need to come back to $x$.',
  },
  {
    id: 'by-parts',
    chapter: 10,
    name: 'Integration by parts',
    tex: "\\int u\\,v'\\,dx = uv - \\int u'\\,v\\,dx",
    note: 'Pick $u$ to be the part that gets simpler when differentiated — a power of $x$, or $\\ln x$. If the new integral is worse than the old one, you chose the other way round.',
  },
  {
    id: 'partial-fractions',
    chapter: 10,
    name: 'Splitting a fraction',
    tex: '\\frac{1}{(x-p)(x-q)} = \\frac{1}{p-q}\\left(\\frac{1}{x-p} - \\frac{1}{x-q}\\right)',
    note: 'Nothing integrates a product of two brackets in a denominator; a sum of two simple ones integrates term by term. Factorise first, then find the numerators by comparing coefficients.',
  },
  {
    id: 'arctan-antiderivative',
    chapter: 10,
    name: 'The arctangent integral',
    tex: '\\int \\frac{1}{x^{2} + a^{2}}\\,dx = \\frac{1}{a}\\arctan\\frac{x}{a} + C',
    note: 'A quadratic on the bottom with no real roots ends here. Complete the square, pull the number out so it reads $u^{2} + 1$, and the rest is a linear substitution — $\\arctan(x)$ has derivative $\\frac{1}{1 + x^{2}}$.',
  },
  {
    id: 'polynomial-division',
    chapter: 10,
    name: 'Dividing first',
    tex: '\\frac{N(x)}{D(x)} = Q(x) + \\frac{R(x)}{D(x)}',
    note: 'When the top is the same degree as the bottom or higher, divide. What is left over has a smaller degree than the divisor, and only then is it a shape you have a rule for.',
  },
  {
    id: 'plus-c',
    chapter: 10,
    name: 'The constant of integration',
    tex: '\\int f(x)\\,dx=F(x)+C',
    note: 'An indefinite integral is a family of functions. Without the $+C$ the answer names only one.',
  },
  {
    id: 'definite-integral',
    chapter: 11,
    name: 'Definite integral',
    tex: '\\int_a^b f(x)\\,dx=F(b)-F(a)',
    note: 'No $+C$ once the bounds go in — it cancels.',
  },
  {
    id: 'total-area',
    chapter: 11,
    name: 'Total area',
    tex: 'A=\\int_a^b \\left|f(x)\\right|dx',
    note: 'Where the curve crosses the axis, the integral counts the part underneath as negative. Area does not work that way: split at the crossing and add the sizes.',
  },
  {
    id: 'area-about-y',
    chapter: 11,
    name: 'Area against the y-axis',
    tex: 'A=\\int_c^d g(y)\\,dy',
    note: 'A region held between a curve and the y-axis is measured in horizontal strips, so everything — the function and the bounds — has to be written in $y$.',
  },
  {
    id: 'improper-integral',
    chapter: 11,
    name: 'Improper integrals',
    tex: lines([
      '\\int_{a}^{\\infty} f(x)\\,dx &= \\lim_{b \\to \\infty} \\int_{a}^{b} f(x)\\,dx',
      '\\int_{1}^{\\infty} \\frac{dx}{x^{p}} &\\text{ converges exactly when } p > 1',
      '\\int_{0}^{1} \\frac{dx}{x^{p}} &\\text{ converges exactly when } p < 1',
    ]),
    note: 'An infinite bound and a bound where the integrand blows up are handled the same way: integrate up to a letter, then let the letter go. If that limit is not a finite number, the integral diverges.',
  },
  {
    id: 'symmetric-integral',
    chapter: 11,
    name: 'Symmetric bounds',
    tex: lines([
      '\\text{odd } f &: \\int_{-a}^{a} f(x)\\,dx = 0',
      '\\text{even } f &: \\int_{-a}^{a} f(x)\\,dx = 2\\int_{0}^{a} f(x)\\,dx',
    ]),
    note: 'Look at the bounds before anything else. An odd integrand over bounds symmetric about 0 gives 0 without an antiderivative — which is the whole point when there is none to find.',
  },
  {
    id: 'limit-factor',
    chapter: 13,
    name: 'A limit that looks like 0/0',
    tex: '\\lim_{x\\to a}\\frac{(x-a)g(x)}{(x-a)h(x)} = \\lim_{x\\to a}\\frac{g(x)}{h(x)}',
    note: 'Substituting gives 0/0, which says nothing. The factor causing it cancels — x never actually equals a, so dividing by $x-a$ is allowed.',
  },
  {
    id: 'limit-infinity',
    chapter: 13,
    name: 'Limits at infinity',
    tex: '\\lim_{x\\to\\infty}\\frac{a_nx^{n}+\\dots}{b_mx^{m}+\\dots} = \\begin{cases}0 & n<m\\\\ \\frac{a_n}{b_m} & n=m\\end{cases}',
    note: 'Divide top and bottom by the highest power in the bottom. Everything with an x left underneath it goes to zero and only the leading behaviour survives.',
  },
  {
    id: 'lhopital',
    chapter: 13,
    name: "L'Hôpital's rule",
    tex: '\\lim_{x\\to a}\\frac{f(x)}{g(x)} = \\lim_{x\\to a}\\frac{f\'(x)}{g\'(x)}',
    note: 'Only for 0/0 and ∞/∞, and it is the derivatives separately — never the quotient rule. Check the form before using it, every time.',
  },
  {
    id: 'limit-constants',
    chapter: 13,
    name: 'Making a limit come out',
    tex: "\\lim_{x\\to a}\\frac{N(x)}{(x-a)^{2}} = L \\;\\Rightarrow\\; N(a) = 0,\\ N'(a) = 0,\\ L = \\tfrac{1}{2}N''(a)",
    note: "A bottom that goes to $0$ needs a top that goes to $0$ as well, or the fraction blows up. Each round of l'Hôpital gives one equation for the missing numbers, and the last round gives the value.",
  },
  {
    id: 'continuity',
    chapter: 13,
    name: 'Continuity at a point',
    tex: '\\lim_{x\\uparrow a}f(x) = \\lim_{x\\downarrow a}f(x) = f(a)',
    note: 'Three things, all equal: what it approaches from the left, from the right, and what it actually is there. A piecewise definition is continuous exactly where the two pieces meet.',
  },
  {
    id: 'asymptote',
    chapter: 13,
    name: 'Asymptotes',
    tex: lines([
      '\\text{vertical} &: \\text{where the denominator is } 0',
      '\\text{horizontal} &: y = \\lim_{x\\to\\pm\\infty}f(x)',
      '\\text{slant} &: \\text{the quotient after dividing}',
    ]),
    note: 'A slant asymptote appears exactly when the top is one degree higher than the bottom — divide, and the remainder dies away.',
  },
  {
    id: 'derivative-definition',
    chapter: 9,
    name: 'Definition of the derivative',
    tex: "f'(a) = \\lim_{h\\to 0}\\frac{f(a+h)-f(a)}{h}",
    note: 'Every rule in the chapter is a shortcut for this. The h in the bottom always cancels — if it does not, the expansion has gone wrong.',
  },
  {
    id: 'higher-derivatives',
    chapter: 9,
    name: 'Higher derivatives',
    tex: "f^{(n)}(x) = \\frac{d}{dx}f^{(n-1)}(x)",
    note: 'For a large n, find the first three or four and look for the cycle rather than grinding: sin and cos repeat every four, and 1/x picks up a factorial and a sign each time.',
  },
  {
    id: 'logarithmic-differentiation',
    chapter: 9,
    name: 'Logarithmic differentiation',
    tex: "\\ln f = g \\Rightarrow f' = f\\cdot g'",
    note: 'For an x in the exponent and an x in the base at once, where neither the power rule nor the exponential rule applies. Take ln, differentiate, multiply back by f.',
  },
  {
    id: 'inflection-point',
    chapter: 9,
    name: 'Convex, concave, inflection',
    tex: "\\begin{aligned} f''(x) > 0 &\\Rightarrow \\text{convex} \\\\ f''(x) < 0 &\\Rightarrow \\text{concave} \\\\ f'' \\text{ changes sign} &\\Rightarrow \\text{inflection point} \\end{aligned}",
    note: "Convex bends up like a cup, concave bends down like a cap. An inflection point is where it switches, and that needs $f''$ to change sign — being zero is not enough.",
  },
  {
    id: 'partial-derivative',
    chapter: 9,
    name: 'Partial derivatives',
    tex: '\\frac{\\partial^{2} f}{\\partial x\\,\\partial y} = \\frac{\\partial}{\\partial x}\\left(\\frac{\\partial f}{\\partial y}\\right) = \\frac{\\partial}{\\partial y}\\left(\\frac{\\partial f}{\\partial x}\\right)',
    note: 'Differentiate in one letter and treat the other as a number. For the mixed one do it twice, once in each; the order does not change the answer, so start with whichever makes the first step shorter.',
  },
  {
    id: 'squeeze',
    chapter: 13,
    name: 'Squeeze theorem',
    tex: 'g \\le f \\le h \\text{ and } \\lim g = \\lim h = L \\Rightarrow \\lim f = L',
    note: "For a factor that oscillates and has no limit of its own. Bound it between -1 and 1, multiply through by the part that does go somewhere, and the middle has nowhere else to go. L'Hôpital cannot help here.",
  },
  {
    id: 'limit-exponential',
    chapter: 13,
    name: 'The 1 to the infinity form',
    tex: lines([
      '\\lim_{x\\to\\infty}\\left(1+\\frac{a}{x}\\right)^{x} &= e^{a}',
      '\\lim f(x)^{g(x)} &= e^{\\lim g(x)\\ln f(x)}',
    ]),
    note: 'A base creeping to 1 with an exponent running to infinity is not 1 — the two race, and e is the result. Either force it into the first shape, or take the logarithm: the exponent comes down as a factor, and what is left is a 0/0 or ∞/∞ for l\'Hôpital.',
  },
  {
    id: 'vector-arithmetic',
    chapter: 12,
    name: 'Adding and scaling vectors',
    tex: lines([
      '\\vec{a} \\pm \\vec{b} &= \\begin{pmatrix}a_1 \\pm b_1\\\\a_2 \\pm b_2\\end{pmatrix}',
      'k\\vec{a} &= \\begin{pmatrix}ka_1\\\\ka_2\\end{pmatrix}',
      '\\vec{PQ} &= \\vec{q} - \\vec{p}',
    ]),
    note: 'Componentwise, always. Drawn, a sum is tip to tail; head minus tail is the arrow between two points, in that order.',
  },
  {
    id: 'vector-length',
    chapter: 12,
    name: 'Length of a vector',
    tex: '\\left|\\vec{a}\\right| = \\sqrt{a_1^{2}+a_2^{2}}',
    note: 'Pythagoras on the components. Leave the root standing — an exact length is the answer, a decimal is not.',
  },
  {
    id: 'dot-product',
    chapter: 12,
    name: 'Dot product',
    tex: lines([
      '\\vec{a}\\cdot\\vec{b} &= a_1b_1 + a_2b_2',
      '&= \\left|\\vec{a}\\right|\\left|\\vec{b}\\right|\\cos\\theta',
    ]),
    note: 'It produces a number, not a vector. Zero means perpendicular; the sign of the dot product is the sign of the cosine, so it tells you sharp or blunt without finding the angle.',
  },
  {
    id: 'area-between',
    chapter: 11,
    name: 'Area between two curves',
    tex: 'A=\\int_a^b \\left(f(x)-g(x)\\right)dx',
    note: 'Upper curve minus lower, and split the integral wherever they cross.',
  },
];
